version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: django_container
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DJANGO_SECRET_KEY='django-insecure-v0=%5snki&wa=c*khm0mvr74tzb%zt+u0cq8e4h1-@(tncz5#@'
      - DJANGO_DEBUG=False
    ports:
      - "80:8000"
    volumes:
      - django_db_data:/app/db.sqlite3

volumes:
  django_db_data:
