# Generated by Django 4.2.5 on 2023-10-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcourse',
            name='image',
            field=models.ImageField(upload_to='rcourse_images'),
        ),
    ]
