# Generated by Django 4.2.5 on 2023-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rcourse',
            name='video_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
