# Generated by Django 4.2.5 on 2023-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_course_video_link_rcourse_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcourse',
            name='announcements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rcourse',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rcourse',
            name='q_and_a',
            field=models.TextField(blank=True),
        ),
    ]
