# Generated by Django 5.0.1 on 2024-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ytcourse_ytvideo_ytcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
