# Generated by Django 5.0.1 on 2024-01-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_ytvideo_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytvideo',
            name='course',
        ),
        migrations.DeleteModel(
            name='YTComment',
        ),
        migrations.DeleteModel(
            name='YTCourse',
        ),
        migrations.DeleteModel(
            name='YTVideo',
        ),
    ]
