# Generated by Django 4.2.5 on 2023-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rcourse_announcements_rcourse_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
